on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Lint & fix
      run: npx eslint . --fix --ext .js
    - name: Check for autofixes
      run: git status | grep modified
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'autofix'
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: 'autofix'

