on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Lint & fix
      run: npx eslint . --fix --ext .js
    - name: Check for autofixes
      run: git status | grep modified
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: ${{ github.ref_name }}-autofix
        reviewers: ${{ github.actor }}
